### ISSUE TITLE
Refactor: Ancillary K8s modules should not inherit from KubernetesRawModule

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.kubernetes#219]
[Derived from feedback from @fabianvf]

Ancillary K8s modules such as k8s_service should not inherit from `KubernetesRawModule`. This is problematic in that the inheritance is too broad and includes a lot of implicitly inherited behavior This makes it unclear what is actually shared and sometimes carries through functions or parameters not applicable to the module being implemented.

Examples of inheritance from the KubernetesRawModule:

- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_service.py#L174
- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_log.py#L120
- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_info.py#L138
- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/module_utils/scale.py#L44

Which are based on these classes:

- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/module_utils/common.py#L288
- https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/module_utils/raw.py#L60

These ancillary K8s modules should inherit from `AnsibleModule` directly rather  KubernetesRawModule and use either bare methods in the `common.py` or if the state is relevant belong in something like the `K8sAnsibleMixin` (https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/module_utils/common.py#L162), which should not implement `AnsibleModule` functionality. 

Conversely, any broadly useful functions or shared code should be identified and moved out of specific modules and into `common.py.

Related to this, the argspec property should be not be included in `K8sAnsibleMixin` to avoid similar unintended inheritance with modules where arguments are not relevant.

- [x] Relocate generally applicable functions inherited from `KubernetesRawModule` to `K8sAnsibleMixin` or `common.py` depending on use
- [x] Move any identified broadly useful functions or shared code in specific modules to `common.py`
- [x] Change inheritance of ancillary k8s modules to use `AnsibleModule` and apply relocated functions from `K8sAnsibleMixin` or `common.py` as necessary.
- [x] Remove argspec property from `K8sAnsibleMixin` moving to specific argspecs in each module
- [ ] Identify any ways the code could be refactored to be "more testable"
- [ ] Adjust unit tests as needed to work with refactored code

**Comment by Akasurde** [comment]
- [ ] https://github.com/ansible-collections/community.kubernetes/pull/223

**Comment by Akasurde** [comment]
All PRs are merged and can be closed.
